title: Tahsin Masruf
logo: ![Tahsin Masruf](tahsinmasruf.github.io/assets/logo.png)
description: Researcher Enthusiast | ML/Data Engineer | Data & Machine Learning
remote_theme: pages-themes/slate@v0.2.0
